"""Core logic for `datacontract dbt sync`."""

from __future__ import annotations

import json
import logging
import re
import shutil
import subprocess
from dataclasses import dataclass, field
from enum import Enum
from io import StringIO
from pathlib import Path
from typing import Any, Dict, List, Optional, Set, Tuple

import yaml
from open_data_contract_standard.model import (
    DataQuality,
    OpenDataContractStandard,
    SchemaObject,
    SchemaProperty,
)
from ruamel.yaml import YAML
from ruamel.yaml.comments import CommentedMap, CommentedSeq
from ruamel.yaml.util import load_yaml_guess_indent

from datacontract.integration.dbt_test_mapping import field_to_data_tests, get_logical_type_option
from datacontract.lint.resolve import resolve_data_contract
from datacontract.model.exceptions import DataContractException
from datacontract.model.run import Check, ResultEnum, Run

logger = logging.getLogger(__name__)

META_NAMESPACE = "datacontract_cli"
# Header substring identifying a sidecar file the CLI owns wholesale (safe to rewrite / delete).
SIDECAR_MARKER = "AUTO-GENERATED by `datacontract dbt sync`"


def _load_dbt_project_config(project_dir: Path) -> dict:
    try:
        with (project_dir / "dbt_project.yml").open("r", encoding="utf-8") as f:
            cfg = yaml.safe_load(f) or {}
    except (OSError, yaml.YAMLError):
        cfg = {}
    return cfg if isinstance(cfg, dict) else {}


def _read_dbt_project_paths(project_dir: Path) -> Tuple[List[Path], List[Path]]:
    """Return (model_paths, test_paths) absolute, honoring `dbt_project.yml`."""
    dbt_project_config = _load_dbt_project_config(project_dir)
    raw_models = (
        dbt_project_config.get("model-paths") if isinstance(dbt_project_config.get("model-paths"), list) else None
    )
    raw_tests = dbt_project_config.get("test-paths") if isinstance(dbt_project_config.get("test-paths"), list) else None
    model_paths = [(project_dir / p).resolve() for p in (raw_models or ["models"]) if isinstance(p, str)]
    test_paths = [(project_dir / p).resolve() for p in (raw_tests or ["tests"]) if isinstance(p, str)]

    # use dbt defaults as fallback
    if not model_paths:
        model_paths = [(project_dir / "models").resolve()]
    if not test_paths:
        test_paths = [(project_dir / "tests").resolve()]
    return model_paths, test_paths


def _resolved_generated_dirs(project_dir: Path) -> Tuple[Path, Path]:
    """Absolute (generated_models_dir, generated_tests_dir) for the configured project."""
    model_paths, test_paths = _read_dbt_project_paths(project_dir)
    return model_paths[0] / META_NAMESPACE, test_paths[0] / META_NAMESPACE


def _resolved_target_dir(project_dir: Path) -> Path:
    """Absolute path of dbt's artifact directory (default `target/`); honors `target-path`."""
    configured_target = _load_dbt_project_config(project_dir).get("target-path")
    return (project_dir / (configured_target if isinstance(configured_target, str) else "target")).resolve()


class ModelResolution(str, Enum):
    name = "name"
    physicalName = "physicalName"


# ---------------------------------------------------------------------------
# Contract / project resolution
# ---------------------------------------------------------------------------


def find_contract(search_dir: Path) -> Path:
    """Recursive `*.odcs.yaml` search; raise on 0 or >1 matches."""
    candidates = sorted(p for p in search_dir.rglob("*.odcs.yaml") if p.is_file())
    if not candidates:
        raise DataContractException(
            type="dbt_sync",
            name="resolve contract",
            reason=(
                f"No `*.odcs.yaml` found below {search_dir}. "
                "Pass the contract path explicitly: `datacontract dbt sync <contract>`."
            ),
            engine="dbt-sync",
        )
    if len(candidates) > 1:
        shown = candidates[:10]
        listing = "\n  - ".join(str(c.relative_to(search_dir)) for c in shown)
        more = f"\n  ... and {len(candidates) - len(shown)} more" if len(candidates) > len(shown) else ""
        raise DataContractException(
            type="dbt_sync",
            name="resolve contract",
            reason=(
                f"Multiple `*.odcs.yaml` files found below {search_dir}:\n  - {listing}{more}\n"
                "Pass one explicitly: `datacontract dbt sync <contract>`."
            ),
            engine="dbt-sync",
        )
    return candidates[0]


def _ensure_dbt_project(project_dir: Path) -> None:
    if not (project_dir / "dbt_project.yml").is_file():
        raise DataContractException(
            type="dbt_sync",
            name="resolve dbt project",
            reason=(
                f"`dbt_project.yml` not found in {project_dir}. Pass `--project-dir` to point at a dbt project root."
            ),
            engine="dbt-sync",
        )


def check_dbt_on_path() -> str:
    dbt_path = shutil.which("dbt")
    if not dbt_path:
        raise DataContractException(
            type="dbt_sync",
            name="dbt preflight",
            reason="""\
dbt not found on PATH. If you want to update the dbt project without running the tests, pass `--skip-tests`.

Otherwise the dbt adapter that matches your warehouse, e.g.:
  pip install dbt-postgres        # Postgres
  pip install dbt-snowflake       # Snowflake
  pip install dbt-bigquery        # BigQuery
  pip install dbt-databricks      # Databricks
  pip install dbt-duckdb          # DuckDB (for local testing)

Full list of adapters: https://docs.getdbt.com/docs/supported-data-platforms
Install guide: https://docs.getdbt.com/docs/core/installation-overview""",
            engine="dbt-sync",
        )
    return dbt_path


# ---------------------------------------------------------------------------
# Model resolution
# ---------------------------------------------------------------------------


def resolve_model_names(
    odcs: OpenDataContractStandard,
    strategy: ModelResolution,
    schema_filter: str = "all",
) -> dict[str, str]:
    """Map `schema.name` → dbt model name. Raise if any schema is unresolvable under the strategy."""
    mapping: dict[str, str] = {}
    schemas = odcs.schema_ or []
    if schema_filter != "all":
        schemas = [s for s in schemas if s.name == schema_filter]
        if not schemas:
            available = ", ".join(s.name for s in (odcs.schema_ or []) if s.name) or "(none)"
            raise DataContractException(
                type="dbt_sync",
                name="resolve schema",
                reason=f"Schema `{schema_filter}` not found in contract. Available: {available}.",
                engine="dbt-sync",
            )
    missing_physical: List[str] = []
    for schema_obj in schemas:
        if not schema_obj.name:
            continue
        if strategy == ModelResolution.name:
            mapping[schema_obj.name] = schema_obj.name
        elif strategy == ModelResolution.physicalName:
            if schema_obj.physicalName:
                mapping[schema_obj.name] = schema_obj.physicalName
            else:
                missing_physical.append(schema_obj.name)
    if missing_physical:
        listing = ", ".join(f"`{n}`" for n in missing_physical)
        raise DataContractException(
            type="dbt_sync",
            name="resolve model",
            reason=(
                f"`--model-resolution physicalName` was requested but the following schema(s) "
                f"have no `physicalName` set: {listing}. Either set `physicalName` in the contract, "
                "or use `--model-resolution name`."
            ),
            engine="dbt-sync",
        )
    return mapping


# ---------------------------------------------------------------------------
# YAML round-trip (ruamel) — preserve formatting as far as possible
# ---------------------------------------------------------------------------


def _make_yaml(*, sequence: int = 4, offset: int = 2) -> YAML:
    yaml = YAML(typ="rt")
    yaml.preserve_quotes = True
    yaml.width = 4096  # don't wrap long descriptions / regex patterns
    yaml.indent(mapping=2, sequence=sequence, offset=offset)
    return yaml


def _guess_indent(text: str) -> Tuple[int, int]:
    """Best-effort (sequence_indent, block_seq_offset) matching the file's own list style."""
    try:
        _, _, offset = load_yaml_guess_indent(text)
    except Exception:
        offset = 2
    return offset + 2, offset


# ---------------------------------------------------------------------------
# Test emission
# ---------------------------------------------------------------------------


def _normalize_severity(severity: Optional[str]) -> str:
    if severity and severity.lower() in {"error", "critical", "high", "fatal"}:
        return "error"
    return "warn"


def _check_type_for_generic_test(test: Any) -> Optional[str]:
    """Map a dbt generic test entry (string or `{name: args}` dict) to a `Check.type` value."""
    dbt_test_name = None
    if isinstance(test, str):
        dbt_test_name = test
    if isinstance(test, dict) and len(test) == 1:
        ((name, _),) = test.items()
        dbt_test_name = name

    return {
        "not_null": "field_required",
        "unique": "field_unique",
        "accepted_values": "field_enum",
        "relationships": "field_relationships",
        "dbt_utils.unique_combination_of_columns": "model_unique_combination",
    }.get(dbt_test_name)


def _qualified_check(model: str, field: Optional[str], check_type: str) -> str:
    """Fully-qualified check key in the `CheckSpec.key` form. Mirrors the native engine's
    keys so a dbt-sync run reports the same `Check.key` shape as `datacontract test`.
    """
    return f"{model}__{field}__{check_type}" if field else f"{model}__{check_type}"


def _attach_test_config(
    test: Any,
    severity: str,
    description: Optional[str] = None,
    check_type: Optional[str] = None,
    model: Optional[str] = None,
    field: Optional[str] = None,
) -> Any:
    """Wrap a test entry with `config: { severity, meta }` and an optional `description`.

    Strings (`"not_null"`) become single-key dicts so the config can ride along
    in the same form dbt accepts.
    """
    config: dict = {"severity": severity}
    if check_type:
        config["meta"] = {META_NAMESPACE: {"check": _qualified_check(model, field, check_type)}}
    if isinstance(test, str):
        body: dict = {"config": config}
        if description:
            body["description"] = description
        return {test: body}
    if isinstance(test, dict) and len(test) == 1:
        ((name, args),) = test.items()
        merged = dict(args) if isinstance(args, dict) else {"value": args}
        merged["config"] = config
        if description:
            merged["description"] = description
        return {name: merged}
    return test


def _describe_dbt_test(test: Any, field_name: Optional[str], model_name: str) -> Optional[str]:
    """Synthesize a human-readable description for a dbt test entry.

    Similar to the check names in `datacontract/engines/checks/create_checks.py`, but for dbt.
    """
    if isinstance(test, str):
        if test == "not_null":
            return f"Check that field {field_name} has no missing values"
        if test == "unique":
            return f"Check that field {field_name} has no duplicate values"
        return None
    if isinstance(test, dict) and len(test) == 1:
        ((name, args),) = test.items()
        if not isinstance(args, dict):
            return None
        if name == "accepted_values":
            values = args.get("values")
            if isinstance(values, list) and len(values) == 1:
                return f"Check that field {field_name} is equal to {values[0]}"
            return f"Check that field {field_name} only contains enum values {values}"
        if name == "relationships":
            return f"Check that field {field_name} references {args.get('to')}.{args.get('field')}"
        if name == "dbt_utils.unique_combination_of_columns":
            cols = args.get("combination_of_columns") or []
            return f"Check that model {model_name} has a unique combination of columns {', '.join(cols)}"
    return None


def _describe_field_bound(prop: SchemaProperty, kind: str) -> Optional[str]:
    """Human-readable descriptions for the singular SQL tests `_field_singular_tests` emits.

    `kind` is one of `"length"`, `"pattern"`, `"range"`.
    """
    if kind == "length":
        min_length = get_logical_type_option(prop, "minLength")
        max_length = get_logical_type_option(prop, "maxLength")
        if min_length is not None and max_length is not None:
            return f"Check that field {prop.name} has a length between {min_length} and {max_length}"
        if min_length is not None:
            return f"Check that field {prop.name} has a length of at least {min_length}"
        if max_length is not None:
            return f"Check that field {prop.name} has a length of at most {max_length}"
        return None
    if kind == "pattern":
        pattern = get_logical_type_option(prop, "pattern")
        return f"Check that field {prop.name} matches regex pattern {pattern}"
    if kind == "range":
        parts = []
        for key, label in (
            ("minimum", "an inclusive minimum of"),
            ("maximum", "an inclusive maximum of"),
            ("exclusiveMinimum", "a strict minimum of"),
            ("exclusiveMaximum", "a strict maximum of"),
        ):
            value = get_logical_type_option(prop, key)
            if value is not None:
                parts.append(f"{label} {value}")
        return f"Check that field {prop.name} has " + " and ".join(parts) if parts else None
    return None


_REL_SOURCE_RE = re.compile(r'source\(\s*"[^"]*"\s*,\s*"([^"]+)"\s*\)')


def _rewrite_relationships_to_ref(tests: list) -> list:
    """Rewrite the helper's `to: source(...)` to `to: ref('<table>')`.

    Sync targets the user's dbt models, so `ref()` is correct. The helper is
    shared with `export dbt`, which legitimately wants `source()`.
    """
    out = []
    for t in tests:
        if isinstance(t, dict) and "relationships" in t and isinstance(t["relationships"], dict):
            rel = dict(t["relationships"])
            to_value = rel.get("to") or ""
            m = _REL_SOURCE_RE.match(to_value)
            if m:
                rel["to"] = f"ref('{m.group(1)}')"
            out.append({"relationships": rel})
        else:
            out.append(t)
    return out


def _slugify(value: str) -> str:
    return re.sub(r"[^a-z0-9_]", "_", value.lower()).strip("_") or "quality"


def _quality_label(quality: DataQuality, fallback_idx: int) -> str:
    if quality.name:
        return quality.name
    if quality.description:
        return quality.description[:40] + "..."
    return f"q{fallback_idx}"


# ---------------------------------------------------------------------------
# Singular SQL test generation
# ---------------------------------------------------------------------------


@dataclass
class SingularTest:
    filename: str
    sql: str
    description: Optional[str]


# ---------------------------------------------------------------------------
# Schema → outputs
# ---------------------------------------------------------------------------


def _sql_literal(value: Any) -> str:
    if isinstance(value, bool):
        return "TRUE" if value else "FALSE"
    if isinstance(value, str):
        return "'" + value.replace("'", "''") + "'"
    return str(value)


def _bound_violation_predicate(quality: DataQuality) -> Optional[str]:
    """Build a SQL predicate over `metric_value` that is TRUE iff any bound on `quality` is violated.

    Bounds present on the quality are combined with `OR` (any violated bound fails the test).
    Returns None if the quality has no bound (the contract author forgot to set `mustBe*`).
    """
    parts: List[str] = []
    if quality.mustBe is not None:
        parts.append(f"metric_value <> {_sql_literal(quality.mustBe)}")
    if quality.mustNotBe is not None:
        parts.append(f"metric_value = {_sql_literal(quality.mustNotBe)}")
    if quality.mustBeGreaterThan is not None:
        parts.append(f"metric_value <= {_sql_literal(quality.mustBeGreaterThan)}")
    if quality.mustBeGreaterOrEqualTo is not None:
        parts.append(f"metric_value < {_sql_literal(quality.mustBeGreaterOrEqualTo)}")
    if quality.mustBeLessThan is not None:
        parts.append(f"metric_value >= {_sql_literal(quality.mustBeLessThan)}")
    if quality.mustBeLessOrEqualTo is not None:
        parts.append(f"metric_value > {_sql_literal(quality.mustBeLessOrEqualTo)}")
    if quality.mustBeBetween is not None and len(quality.mustBeBetween) == 2:
        lo, hi = quality.mustBeBetween
        parts.append(f"metric_value < {_sql_literal(lo)}")
        parts.append(f"metric_value > {_sql_literal(hi)}")
    if quality.mustNotBeBetween is not None and len(quality.mustNotBeBetween) == 2:
        lo, hi = quality.mustNotBeBetween
        parts.append(f"(metric_value >= {_sql_literal(lo)} AND metric_value <= {_sql_literal(hi)})")
    if not parts:
        return None
    return "metric_value IS NULL OR " + " OR ".join(parts)


def _singular_tests_for_qualities(
    qualities: Optional[list],
    contract_id: str,
    model: str,
    run: Run,
    *,
    label_prefix: str = "",
    field: Optional[str] = None,
) -> List[SingularTest]:
    """Generate singular tests for ODCS quality entries that have an associated `query` and bound."""
    out: List[SingularTest] = []
    for idx, quality in enumerate(qualities or [], start=1):
        if not quality.query:
            continue
        predicate = _bound_violation_predicate(quality)
        test_label = f"{label_prefix}{_quality_label(quality, idx)}" if label_prefix else _quality_label(quality, idx)
        if predicate is None:
            run.log_warn(
                f"Skipping singular SQL test `{test_label}` on `{model}`: quality has a `query` but no `mustBe*` bound."
            )
            continue
        severity = _normalize_severity(quality.severity)
        filename = f"{_slugify(contract_id)}__{_slugify(model)}__{_slugify(test_label)}"
        out.append(
            SingularTest(
                filename=f"{filename}.sql",
                sql=_build_singular_sql(
                    quality.query,
                    predicate,
                    severity,
                    contract_id,
                    model,
                    check_type="custom_sql",
                    field=field,
                    description=quality.description,
                ),
                description=quality.description,
            )
        )
    return out


def _format_dc_meta(
    model: str, field: Optional[str] = None, description: Optional[str] = None, check: Optional[str] = None
) -> str:
    """Render the `meta={...}` arg for dbt `config()` so singular tests carry their contract metadata."""
    block: dict = {
        "check": _qualified_check(model, field, check) if check else None,
        "generated": True,  # always true, because singular SQL tests are always regenerated
        "include_in_tests": True,
        "model": model,
    }
    if field:
        block["field"] = field
    if description:
        block["description"] = description
    return f"meta={json.dumps({META_NAMESPACE: block})}"


def _build_singular_sql(
    query: str,
    violation_predicate: str,
    severity: str,
    contract_id: str,
    model: str,
    *,
    check_type: str,
    field: Optional[str] = None,
    description: Optional[str] = None,
) -> str:
    # The ODCS query is expected to yield a single-column scalar metric. We alias that
    # column to `metric_value` via the CTE column list, then return rows only when the
    # bound is violated — dbt singular-test semantics (rows returned = test failed).
    return (
        f"-- AUTO-GENERATED by `datacontract dbt sync`. Do not edit.\n"
        f"-- Source contract: {contract_id} (model: {model})\n"
        f"{{{{ config(severity='{severity}', {_format_dc_meta(model, field, description, check_type)}) }}}}\n"
        f"WITH _dc_metric (metric_value) AS (\n"
        f"{query.rstrip()}\n"
        f")\n"
        f"SELECT metric_value FROM _dc_metric WHERE {violation_predicate}\n"
    )


def _row_count_singular_test(quality: DataQuality, contract_id: str, model: str) -> Optional[SingularTest]:
    """Singular SQL test for a table-level `rowCount` quality without an explicit `query`."""
    predicate = _bound_violation_predicate(quality)
    if predicate is None:
        return None
    description = quality.description or _describe_row_count_quality(quality, model)
    return SingularTest(
        filename=_slugify(f"{contract_id}__{model}__{_quality_label(quality, 1)}") + ".sql",
        sql=_build_singular_sql(
            f"SELECT COUNT(*) FROM {{{{ ref('{model}') }}}}",
            predicate,
            _normalize_severity(quality.severity),
            contract_id,
            model,
            check_type="row_count",
            description=description,
        ),
        description=description,
    )


def _describe_row_count_quality(quality: DataQuality, model: str) -> Optional[str]:
    if quality.mustBe is not None:
        return f"Check that model {model} has exactly {quality.mustBe} rows"
    if quality.mustNotBe is not None:
        return f"Check that model {model} does not have exactly {quality.mustNotBe} rows"
    if quality.mustBeGreaterThan is not None:
        return f"Check that model {model} has more than {quality.mustBeGreaterThan} rows"
    if quality.mustBeGreaterOrEqualTo is not None:
        return f"Check that model {model} has at least {quality.mustBeGreaterOrEqualTo} rows"
    if quality.mustBeLessThan is not None:
        return f"Check that model {model} has fewer than {quality.mustBeLessThan} rows"
    if quality.mustBeLessOrEqualTo is not None:
        return f"Check that model {model} has at most {quality.mustBeLessOrEqualTo} rows"
    if quality.mustBeBetween is not None and len(quality.mustBeBetween) == 2:
        return f"Check that model {model} has between {quality.mustBeBetween[0]} and {quality.mustBeBetween[1]} rows"
    if quality.mustNotBeBetween is not None and len(quality.mustNotBeBetween) == 2:
        return (
            f"Check that model {model} has a row count outside "
            f"{quality.mustNotBeBetween[0]} to {quality.mustNotBeBetween[1]}"
        )
    return None


# ---------------------------------------------------------------------------
# Field-level bound singular SQL (length / regex / numeric range)
#
# We emit these as singular SQL so generated dbt projects don't need
# `dbt_expectations` in their `packages.yml`. Each test returns rows that
# violate the bound (dbt singular-test convention).
# ---------------------------------------------------------------------------


def _quote_identifier(name: str) -> str:
    return '"' + name.replace('"', '""') + '"'


def _regex_violation_jinja(column: str, pattern: str) -> str:
    """Adapter-portable 'col does NOT match pattern' fragment.

    Dispatches on `target.type` because regex syntax is one of the least-portable
    parts of SQL: BigQuery uses `REGEXP_CONTAINS`, Snowflake/Oracle use
    `REGEXP_LIKE`, and Postgres / DuckDB / Redshift use the POSIX `~` operator.
    """
    escaped = pattern.replace("'", "''")
    return (
        "{% if target.type == 'bigquery' %}"
        f"NOT REGEXP_CONTAINS(CAST({column} AS STRING), '{escaped}')"
        "{% elif target.type == 'snowflake' %}"
        f"NOT REGEXP_LIKE(CAST({column} AS VARCHAR), '{escaped}')"
        "{% else %}"
        f"CAST({column} AS VARCHAR) !~ '{escaped}'"
        "{% endif %}"
    )


def _field_bound_predicates(prop: SchemaProperty) -> List[Tuple[str, str]]:
    """For `prop`, yield `(kind, sql_predicate)` for each declared bound, where `kind` is one of `"length"` / `"pattern"` / `"range"`.

    `sql_predicate` is TRUE only for rows that violate the bound. Length checks
    fire when the value is non-null but its length is out of range; numeric
    range checks fire when the value is non-null and outside the range; regex
    fires when the value does not match. NULLs are filtered upstream with
    `WHERE col IS NOT NULL`.
    """
    column = _quote_identifier(prop.name)
    pairs: List[Tuple[str, str]] = []

    min_length = get_logical_type_option(prop, "minLength")
    max_length = get_logical_type_option(prop, "maxLength")
    if min_length is not None or max_length is not None:
        parts: List[str] = []
        if min_length is not None:
            parts.append(f"LENGTH({column}) < {min_length}")
        if max_length is not None:
            parts.append(f"LENGTH({column}) > {max_length}")
        pairs.append(("length", " OR ".join(parts)))

    pattern = get_logical_type_option(prop, "pattern")
    if pattern is not None:
        pairs.append(("pattern", _regex_violation_jinja(column, pattern)))

    minimum = get_logical_type_option(prop, "minimum")
    maximum = get_logical_type_option(prop, "maximum")
    exclusive_minimum = get_logical_type_option(prop, "exclusiveMinimum")
    exclusive_maximum = get_logical_type_option(prop, "exclusiveMaximum")
    range_parts: List[str] = []
    if minimum is not None:
        range_parts.append(f"{column} < {_sql_literal(minimum)}")
    if maximum is not None:
        range_parts.append(f"{column} > {_sql_literal(maximum)}")
    if exclusive_minimum is not None:
        range_parts.append(f"{column} <= {_sql_literal(exclusive_minimum)}")
    if exclusive_maximum is not None:
        range_parts.append(f"{column} >= {_sql_literal(exclusive_maximum)}")
    if range_parts:
        pairs.append(("range", " OR ".join(range_parts)))

    return pairs


def _build_row_violation_sql(
    *,
    model: str,
    field: str,
    column_null_filter: str,
    violation_predicate: str,
    severity: str,
    contract_id: str,
    label: str,
    check_type: str,
    description: Optional[str] = None,
) -> str:
    return (
        f"-- AUTO-GENERATED by `datacontract dbt sync`. Do not edit.\n"
        f"-- Source contract: {contract_id} (model: {model}, check: {label})\n"
        f"{{{{ config(severity='{severity}', {_format_dc_meta(model, field, description, check_type)}) }}}}\n"
        f"SELECT *\n"
        f"FROM {{{{ ref('{model}') }}}}\n"
        f"WHERE {column_null_filter} IS NOT NULL\n"
        f"  AND ({violation_predicate})\n"
    )


def _field_singular_tests(prop: SchemaProperty, contract_id: str, model: str) -> List[SingularTest]:
    """Singular SQL tests for `logicalTypeOptions` bounds on `prop` (length / regex / range)."""
    column = _quote_identifier(prop.name)
    out: List[SingularTest] = []
    for kind, predicate in _field_bound_predicates(prop):
        label = f"{prop.name}__{kind}"
        description = _describe_field_bound(prop, kind)
        out.append(
            SingularTest(
                filename=_slugify(f"{contract_id}__{model}__{label}") + ".sql",
                sql=_build_row_violation_sql(
                    model=model,
                    field=prop.name,
                    column_null_filter=column,
                    violation_predicate=predicate,
                    severity="warn",
                    contract_id=contract_id,
                    label=label,
                    check_type={"length": "field_length", "pattern": "field_regex", "range": "field_range"}[kind],
                    description=description,
                ),
                description=description,
            )
        )
    return out


def _model_data_tests(
    schema_obj: SchemaObject, run: Run, contract_id: str, model: str
) -> Tuple[list, List[SingularTest]]:
    """Model-level outputs: composite-PK YAML test + table-level rowCount as singular SQL.

    Returns ``(yaml_tests, singular_tests)``. Row-count qualities without a
    ``query`` field are emitted as singular SQL (rather than dbt_expectations
    YAML) so generated projects stay free of external macro dependencies.
    """
    yaml_tests: list = []
    singular_tests: List[SingularTest] = []
    pk_cols = [p.name for p in (schema_obj.properties or []) if p.primaryKey]
    if len(pk_cols) > 1:
        pk_test = {"dbt_utils.unique_combination_of_columns": {"combination_of_columns": pk_cols}}
        yaml_tests.append(
            _attach_test_config(
                pk_test,
                severity="warn",
                description=_describe_dbt_test(pk_test, None, model),
                check_type="model_unique_combination",
                model=model,
            )
        )
    for q in schema_obj.quality or []:
        if q.query:
            continue  # singular SQL handles it via _singular_tests_for_qualities
        if q.metric and q.metric.lower() == "rowcount":
            test = _row_count_singular_test(q, contract_id, model)
            if test is None:
                run.log_warn(f"Skipping unsupported row-count quality on `{schema_obj.name}`")
                continue
            singular_tests.append(test)
        else:
            run.log_warn(f"Skipping unsupported quality on `{schema_obj.name}`: metric={q.metric!r}")
    return yaml_tests, singular_tests


def _column_dict(
    prop: SchemaProperty, odcs: OpenDataContractStandard, single_pk_name: Optional[str], model_name: str, run: Run
) -> dict:
    column: dict = {"name": prop.name}
    base = field_to_data_tests(
        prop,
        is_primary_key=bool(prop.primaryKey),
        is_single_pk=(prop.name == single_pk_name),
        supports_constraints=False,
        source_name=odcs.id or "_source",
        include_dbt_expectations_bounds=False,
    )
    base = _rewrite_relationships_to_ref(base)
    tests = [
        _attach_test_config(
            test,
            severity="warn",
            description=_describe_dbt_test(test, prop.name, model_name),
            check_type=_check_type_for_generic_test(test),
            model=model_name,
            field=prop.name,
        )
        for test in base
    ]

    for data_quality in prop.quality or []:
        if data_quality.metric and data_quality.metric.lower() == "invalidvalues":
            continue
        if data_quality.query:
            continue
        if data_quality.mustBe is not None:
            entry = {"accepted_values": {"values": [data_quality.mustBe]}}
            tests.append(
                _attach_test_config(
                    entry,
                    _normalize_severity(data_quality.severity),
                    description=data_quality.description or _describe_dbt_test(entry, prop.name, model_name),
                    check_type="field_enum",
                    model=model_name,
                    field=prop.name,
                )
            )
            continue
        run.log_warn(f"Skipping unsupported quality on `{prop.name}`: metric={data_quality.metric!r}")

    if tests:
        column["data_tests"] = tests
    return column


def generate_dbt_tests_for_schema(
    odcs: OpenDataContractStandard,
    schema_obj: SchemaObject,
    model_name: str,
    run: Run,
) -> Tuple[dict, List[SingularTest]]:
    """Build the YAML model dict + list of singular SQL tests for one schema."""
    pk_cols = [p.name for p in (schema_obj.properties or []) if p.primaryKey]
    single_pk_name = pk_cols[0] if len(pk_cols) == 1 else None

    model_dict: dict = {"name": model_name}
    if schema_obj.description:
        model_dict["description"] = schema_obj.description.strip().replace("\n", " ")

    contract_id = odcs.id or "contract"
    model_yaml_tests, model_singulars = _model_data_tests(schema_obj, run, contract_id, model_name)
    if model_yaml_tests:
        model_dict["data_tests"] = model_yaml_tests

    columns: list = []
    for prop in schema_obj.properties or []:
        columns.append(_column_dict(prop, odcs, single_pk_name, model_name, run))
    if columns:
        model_dict["columns"] = columns

    singulars: List[SingularTest] = list(model_singulars)
    # Field-level bounds (length / regex / numeric range) → singular SQL
    for prop in schema_obj.properties or []:
        singulars.extend(_field_singular_tests(prop, contract_id, model_name))
    # Existing `quality.query` singular tests (one CTE per scalar metric)
    for prop in schema_obj.properties or []:
        singulars.extend(
            _singular_tests_for_qualities(
                prop.quality,
                contract_id,
                model_name,
                run,
                label_prefix=f"{prop.name}__",
                field=prop.name,
            )
        )
    singulars.extend(_singular_tests_for_qualities(schema_obj.quality, contract_id, model_name, run))
    _disambiguate_singular_filenames(singulars)

    return model_dict, singulars


def _disambiguate_singular_filenames(singular_tests: List[SingularTest]) -> None:
    """In-place rename so two qualities whose labels slugify identically don't overwrite each other."""
    used: set[str] = set()
    for test in singular_tests:
        if test.filename not in used:
            used.add(test.filename)
            continue
        stem = Path(test.filename).stem
        n = 2
        while f"{stem}__{n}.sql" in used:
            n += 1
        new_filename = f"{stem}__{n}.sql"
        test.filename = new_filename
        used.add(new_filename)


# ---------------------------------------------------------------------------
# File writing
# ---------------------------------------------------------------------------


def _write_singular_sql(project_dir: Path, singular_tests: List[SingularTest]) -> List[Path]:
    """Write the singular `.sql` tests under `<test-paths>/datacontract_cli/`."""
    _, generated_tests_dir = _resolved_generated_dirs(project_dir)
    sql_paths: List[Path] = []
    for s in singular_tests:
        sql_path = generated_tests_dir / s.filename
        sql_path.parent.mkdir(parents=True, exist_ok=True)
        sql_path.write_text(s.sql, encoding="utf-8")
        sql_paths.append(sql_path)
    return sql_paths


# ---------------------------------------------------------------------------
# Generic-test entry helpers (operate on dbt `data_tests` list elements, which
# are either a bare string `"not_null"` or a single-key dict `{name: {...}}`)
# ---------------------------------------------------------------------------


def _test_name(entry: str | dict) -> Optional[str]:
    if isinstance(entry, str):
        return entry
    if isinstance(entry, dict) and len(entry) == 1:
        return next(iter(entry.keys()))
    return None


def _test_body(entry: str | dict) -> dict:
    """The mapping under the test's single key (e.g. `{values:…, config:…}`); `{}` for a bare string."""
    if isinstance(entry, dict) and len(entry) == 1:
        body = next(iter(entry.values()))
        if isinstance(body, dict):
            return body
    return {}


def _meta_block_for_test(entry: str | dict) -> dict:
    """The CLI's `config.meta.datacontract_cli` block on a test entry, or `{}`."""
    meta = (_test_body(entry).get("config") or {}).get("meta") or {}
    block = meta.get(META_NAMESPACE)
    return block if isinstance(block, dict) else {}


def _ensure_membership(entry: dict, dc_check: Optional[str], *, generated: bool) -> None:
    """Stamp the CLI's `config.meta.datacontract_cli` block onto a test.

    `generated=True` marks a test we created; `generated=False` records an adopted user test but
    never downgrades an already-`True` block.
    """
    body = entry[_test_name(entry)]
    config = body.get("config")
    if not isinstance(config, dict):
        config = CommentedMap()
        body["config"] = config
    meta = config.get("meta")
    if not isinstance(meta, dict):
        meta = CommentedMap()
        config["meta"] = meta
    block = meta.get(META_NAMESPACE)
    if not isinstance(block, dict):
        block = CommentedMap()
        meta[META_NAMESPACE] = block

    if "include_in_tests" not in block:
        block["include_in_tests"] = True  # default; a user may flip to false to opt the test out
    if dc_check:
        block["check"] = dc_check
    if generated:
        block["generated"] = True
    elif "generated" not in block:
        block["generated"] = False


def _strip_managed(entry: dict) -> bool:
    """Remove the CLI's `config.meta.datacontract_cli` block from a test, leaving the user's test. True if modified."""
    name = _test_name(entry)
    if name is None or isinstance(entry, str):
        return False
    body = entry[name]
    config = body.get("config")
    if not isinstance(config, dict):
        return False
    changed = False
    meta = config.get("meta")
    if isinstance(meta, dict) and META_NAMESPACE in meta:
        meta.pop(META_NAMESPACE, None)
        if not meta:
            config.pop("meta", None)
        changed = True
    if not config:
        body.pop("config", None)
    return changed


def _collapse_test(entry: str | dict) -> str | dict:
    """Collapse `{name: {}}` back to the bare string `name` (e.g. after stripping our meta from an adopted test)."""
    name = _test_name(entry)
    if name is not None and isinstance(entry, dict) and not entry[name]:
        return name
    return entry


def _find_test_index(seq: list, test_name: str) -> Optional[int]:
    for i, entry in enumerate(seq):
        if _test_name(entry) == test_name:
            return i
    return None


def _reconcile_test(existing: str | dict, desired: dict, dc_check: Optional[str]) -> dict:
    """Update a pre-existing test (string or dict) to satisfy the contract, in dict form.

    Overwrites args to the contract's (contract wins), then ensures membership tags. The user's
    `config` (severity etc.) and any non-arg keys are left untouched.
    """
    name = _test_name(existing)
    if isinstance(existing, str):
        entry: dict = CommentedMap()
        entry[name] = CommentedMap()
    else:
        entry = existing
        if not isinstance(entry.get(name), dict):
            entry[name] = CommentedMap()
    body = entry[name]
    desired_args = {k: v for k, v in _test_body(desired).items() if k not in ("config", "description")}
    for k in [k for k in list(body.keys()) if k not in ("config", "description") and k not in desired_args]:
        del body[k]
    for k, v in desired_args.items():
        body[k] = v
    _ensure_membership(entry, dc_check, generated=False)
    return entry


def _reconcile_data_tests(container: dict, desired_tests: list) -> None:
    """Merge the contract's desired generic tests into `container["data_tests"]` in place."""
    if not desired_tests:
        return
    existing = container.get("data_tests")
    if not isinstance(existing, list):
        existing = CommentedSeq()
    for desired in desired_tests:
        test_name = _test_name(desired)
        if test_name is None:
            continue
        dc_check = _meta_block_for_test(desired).get("check")
        idx = _find_test_index(existing, test_name)
        if idx is None:
            new_entry = CommentedMap(desired) if not isinstance(desired, CommentedMap) else desired
            _ensure_membership(new_entry, dc_check, generated=True)
            existing.append(new_entry)
        else:
            existing[idx] = _reconcile_test(existing[idx], desired, dc_check)
    container["data_tests"] = existing


# ---------------------------------------------------------------------------
# Column / model entry helpers
# ---------------------------------------------------------------------------


def _is_managed_column(col: dict) -> bool:
    meta = col.get("meta")
    block = meta.get(META_NAMESPACE) if isinstance(meta, dict) else None
    return isinstance(block, dict) and block.get("generated") is True


def _mark_managed_column(col: dict) -> None:
    meta = col.get("meta")
    if not isinstance(meta, dict):
        meta = CommentedMap()
        col["meta"] = meta
    block = meta.get(META_NAMESPACE)
    if not isinstance(block, dict):
        block = CommentedMap()
        meta[META_NAMESPACE] = block
    block["generated"] = True


def _find_column(entry: dict, name: str) -> Optional[dict]:
    """Case-insensitive lookup of a column by name (preserves the file's own casing)."""
    target = name.lower()
    for col in entry.get("columns") or []:
        if isinstance(col, dict) and str(col.get("name", "")).lower() == target:
            return col
    return None


def _existing_config(container: dict) -> Optional[dict]:
    config = container.get("config")
    return config if isinstance(config, dict) else None


def _ensure_config(container: dict) -> dict:
    config = container.get("config")
    if not isinstance(config, dict):
        config = CommentedMap()
        container["config"] = config
    return config


def _union_tags(container: dict, new_tags: list, *, reconcile: bool, prune: bool) -> None:
    """Maintain `config.tags` on a model/column entry from ODCS tags.

    `reconcile` (entry wholly ours) / `prune` → mirror the contract (add + drop orphans);
    otherwise union, never dropping the user's own tags. Never creates an empty `config`.
    """
    mirror = reconcile or prune
    config = _existing_config(container)
    existing = config.get("tags") if config else None
    existing = list(existing) if isinstance(existing, list) else None

    if existing is None:
        if not new_tags:
            return  # nothing to add and nothing to mirror away
        result = list(new_tags)
    elif mirror:
        result = [t for t in existing if t in new_tags]
        for t in new_tags:
            if t not in result:
                result.append(t)
    else:
        result = existing
        for t in new_tags:
            if t not in result:
                result.append(t)

    config = _ensure_config(container)
    if result:
        config["tags"] = result
    else:
        config.pop("tags", None)
        if not config:
            container.pop("config", None)


def _set_meta_keys(entry: dict, *, data_contract: Optional[str], owner: Optional[str]) -> None:
    """Make our `config.meta` keys authoritative: write `data_contract`/`owner` from the contract,
    overwriting prior values, and drop a stale `owner` when the contract has no team. Other meta is kept."""
    config = _ensure_config(entry)
    meta = config.get("meta")
    if not isinstance(meta, dict):
        meta = CommentedMap()
        config["meta"] = meta
    if data_contract is not None:
        meta["data_contract"] = data_contract
    if owner is not None:
        meta["owner"] = owner
    else:
        meta.pop("owner", None)


def _meta_data_contract(entry: dict) -> Optional[str]:
    meta = (entry.get("config") or {}).get("meta") or {}
    val = meta.get("data_contract")
    return val if isinstance(val, str) else None


def _remove_our_meta(entry: dict) -> None:
    """Drop the named `config.meta` keys we set, collapsing emptied containers."""
    config = entry.get("config")
    if not isinstance(config, dict):
        return
    meta = config.get("meta")
    if isinstance(meta, dict):
        meta.pop("data_contract", None)
        meta.pop("owner", None)
        if not meta:
            config.pop("meta", None)
    if not config:
        entry.pop("config", None)


# ---------------------------------------------------------------------------
# In-place model YAML editing: locate / merge / cleanup
# ---------------------------------------------------------------------------


def _model_entries(data: Any) -> List[dict]:
    models = data.get("models") if isinstance(data, dict) else None
    return [m for m in models if isinstance(m, dict)] if isinstance(models, list) else []


def _is_owned_sidecar(text: Optional[str]) -> bool:
    """True if a file is a sidecar the CLI owns wholesale (safe to rewrite / delete)."""
    return bool(text) and SIDECAR_MARKER in text[:400]


def _iter_model_yaml_files(model_paths: List[Path], legacy_dir: Path):
    """Yield every `*.yml` / `*.yaml` under `model-paths`, skipping the legacy generated dir."""
    seen: Set[Path] = set()
    legacy_resolved = legacy_dir.resolve()
    for root in model_paths:
        if not root.is_dir():
            continue
        for pattern in ("*.yml", "*.yaml"):
            for path in sorted(root.rglob(pattern)):
                resolved = path.resolve()
                if legacy_resolved == resolved or legacy_resolved in resolved.parents:
                    continue
                if resolved in seen:
                    continue
                seen.add(resolved)
                yield path


def _locate_model_sql(model_paths: List[Path], model_name: str) -> Optional[Path]:
    """First `*.sql` whose filename stem matches `model_name` (case-insensitive)."""
    target = model_name.lower()
    matches: List[Path] = []
    for root in model_paths:
        if not root.is_dir():
            continue
        for path in root.rglob("*.sql"):
            if path.stem.lower() == target:
                matches.append(path)
    return sorted(matches)[0] if matches else None


@dataclass
class RequiredState:
    """What the current contract declares — drives the provenance-aware cleanup pass."""

    scope_models: Dict[str, str] = field(default_factory=dict)  # lower(model) -> model name
    required_tests: Dict[str, Set[Tuple[Optional[str], str]]] = field(default_factory=dict)


def _required_test_keys(model_dict: dict) -> Set[Tuple[Optional[str], str]]:
    keys: Set[Tuple[Optional[str], str]] = set()
    for test in model_dict.get("data_tests") or []:
        name = _test_name(test)
        if name:
            keys.add((None, name))
    for col in model_dict.get("columns") or []:
        col_lower = str(col.get("name", "")).lower()
        for test in col.get("data_tests") or []:
            name = _test_name(test)
            if name:
                keys.add((col_lower, name))
    return keys


@dataclass
class _ModelPlan:
    """One contract schema resolved to the project's actual dbt model, with its desired state."""

    name: str  # effective dbt model name (case as the project has it)
    schema_obj: SchemaObject
    model_dict: dict
    singular_tests: List["SingularTest"]
    sql_path: Optional[Path]  # set only when matched via a `.sql` file (→ sidecar)


def _effective_model_name(
    session: "_EditSession", model_paths: List[Path], contract_model_name: str
) -> Tuple[str, str, Optional[Path]]:
    """Map a contract model name to the project's actual dbt model name (case-insensitive, #1254).

    Returns ``(name, source, sql_path)`` where ``source`` is ``"entry"`` (a YAML model entry
    exists), ``"sql"`` (only a `.sql` exists → sidecar), or ``"missing"`` (no dbt model).
    The returned name preserves the project's casing so `ref()` and dbt patches resolve.
    """
    located = _locate_entry(session, contract_model_name)
    if located is not None:
        entry = located[1]
        return str(entry.get("name") or contract_model_name), "entry", None
    sql_path = _locate_model_sql(model_paths, contract_model_name)
    if sql_path is not None:
        return sql_path.stem, "sql", sql_path
    return contract_model_name, "missing", None


# ---------------------------------------------------------------------------
# Edit session — accumulates YAML edits across the cleanup + merge passes, then
# writes them in one shot.
# ---------------------------------------------------------------------------


@dataclass
class _PlannedFile:
    path: Path
    data: Any
    yaml: YAML
    original_text: Optional[str]  # None => created this run
    deleted: bool = False


class _EditSession:
    def __init__(self) -> None:
        self.files: Dict[Path, _PlannedFile] = {}

    def try_load(self, path: Path) -> Optional[Any]:
        if path in self.files:
            return self.files[path].data
        try:
            text = path.read_text(encoding="utf-8")
            seq_indent, offset = _guess_indent(text)
            y = _make_yaml(sequence=seq_indent, offset=offset)
            data = y.load(text)
        except Exception:
            return None  # unparseable / unreadable → leave the file untouched
        if not isinstance(data, dict):
            return None
        self.files[path] = _PlannedFile(path=path, data=data, yaml=y, original_text=text)
        return data

    def create_sidecar(self, path: Path, entry: dict) -> Any:
        data = CommentedMap()
        data["version"] = 2
        models = CommentedSeq()
        models.append(entry)
        data["models"] = models
        data.yaml_set_start_comment(
            "AUTO-GENERATED by `datacontract dbt sync`. Do not edit.\n"
            "Managed by the data contract; edits will be overwritten on the next sync."
        )
        self.files[path] = _PlannedFile(path=path, data=data, yaml=_make_yaml(), original_text=None)
        return data

    def delete(self, path: Path) -> None:
        pf = self.files.get(path)
        if pf is not None:
            pf.deleted = True

    def _render(self, pf: _PlannedFile) -> str:
        buf = StringIO()
        pf.yaml.dump(pf.data, buf)
        return buf.getvalue()

    def apply(self) -> Tuple[List[Path], List[Path]]:
        written: List[Path] = []
        deleted: List[Path] = []
        for pf in self.files.values():
            if pf.deleted:
                if pf.path.exists():
                    pf.path.unlink()
                    deleted.append(pf.path)
                continue
            new_text = self._render(pf)
            if new_text != (pf.original_text or ""):
                pf.path.parent.mkdir(parents=True, exist_ok=True)
                pf.path.write_text(new_text, encoding="utf-8")
                written.append(pf.path)
        return written, deleted


def _locate_entry(session: _EditSession, model_name: str) -> Optional[Tuple[Path, dict]]:
    """First `models[].name` match across loaded files (case-insensitive, deterministic order)."""
    target = model_name.lower()
    for path in sorted(session.files):
        if session.files[path].deleted:
            continue
        for entry in _model_entries(session.files[path].data):
            if str(entry.get("name", "")).lower() == target:
                return path, entry
    return None


# ---------------------------------------------------------------------------
# Merge: write the contract's desired state into a single model entry
# ---------------------------------------------------------------------------


def _merge_model_entry(
    entry: dict,
    schema_obj: SchemaObject,
    model_dict: dict,
    odcs: OpenDataContractStandard,
    *,
    owned: bool,
    prune: bool,
) -> None:
    """Merge the contract's desired metadata + tests into one dbt model entry, in place."""
    props_by_name = {p.name.lower(): p for p in (schema_obj.properties or []) if p.name}

    # Metadata: description (contract wins), config.meta named keys, model tags.
    desc = model_dict.get("description")
    if desc:
        entry["description"] = desc
    elif owned:
        entry.pop("description", None)
    _set_meta_keys(entry, data_contract=odcs.id, owner=(odcs.team.name if odcs.team else None))
    _union_tags(entry, list(schema_obj.tags or []), reconcile=owned, prune=prune)

    # Model-level generic tests (e.g. composite-PK unique_combination).
    _reconcile_data_tests(entry, model_dict.get("data_tests") or [])

    # Columns.
    contract_cols: Set[str] = set()
    for desired_col in model_dict.get("columns") or []:
        col_name = desired_col["name"]
        contract_cols.add(col_name.lower())
        prop = props_by_name.get(col_name.lower())
        target = _find_column(entry, col_name)
        created = target is None
        if created:
            target = CommentedMap()
            target["name"] = col_name
            cols = entry.get("columns")
            if not isinstance(cols, list):
                cols = CommentedSeq()
                entry["columns"] = cols
            cols.append(target)

        if prop is not None and prop.description:
            target["description"] = prop.description.strip().replace("\n", " ")
        col_tags = list(prop.tags or []) if prop else []
        _union_tags(target, col_tags, reconcile=(owned or created or _is_managed_column(target)), prune=prune)
        _reconcile_data_tests(target, desired_col.get("data_tests") or [])
        if created and not owned:
            _mark_managed_column(target)

    # --prune: strict-mirror the contract's column set (drops user columns too).
    if prune:
        cols = entry.get("columns")
        if isinstance(cols, list):
            kept = CommentedSeq(c for c in cols if str(c.get("name", "")).lower() in contract_cols)
            if kept:
                entry["columns"] = kept
            else:
                entry.pop("columns", None)


# ---------------------------------------------------------------------------
# Cleanup pass — provenance-aware removal of CLI footprint no longer required.
# ---------------------------------------------------------------------------


def _entry_has_footprint(entry: dict) -> bool:
    if _meta_data_contract(entry):
        return True
    if any(_meta_block_for_test(t) for t in (entry.get("data_tests") or [])):
        return True
    for col in entry.get("columns") or []:
        if isinstance(col, dict) and (
            _is_managed_column(col) or any(_meta_block_for_test(t) for t in (col.get("data_tests") or []))
        ):
            return True
    return False


def _entry_in_scope(entry: dict, scope_contract_id: Optional[str], scope_models: Dict[str, str]) -> bool:
    if scope_contract_id is None:
        return _entry_has_footprint(entry)
    return _meta_data_contract(entry) == scope_contract_id or str(entry.get("name", "")).lower() in scope_models


def _clean_tests_in_container(
    container: dict,
    column_key: Optional[str],
    required_keys: Set[Tuple[Optional[str], str]],
    *,
    model_required: bool,
) -> None:
    tests = container.get("data_tests")
    if not isinstance(tests, list):
        return
    survivors = CommentedSeq()
    for entry in tests:
        if not _meta_block_for_test(entry):
            survivors.append(entry)
            continue
        name = _test_name(entry)
        if model_required and (column_key, name) in required_keys:
            survivors.append(entry)  # still required → merge will refresh it
            continue
        if _meta_block_for_test(entry).get("generated") is True:
            continue  # drop the node we created
        _strip_managed(entry)  # drop our meta block, keep the user's test
        survivors.append(_collapse_test(entry))
    if len(survivors):
        container["data_tests"] = survivors
    else:
        container.pop("data_tests", None)


def _clean_model_entry(
    entry: dict,
    *,
    required_keys: Set[Tuple[Optional[str], str]],
    model_required: bool,
) -> None:
    _clean_tests_in_container(entry, None, required_keys, model_required=model_required)
    for col in entry.get("columns") or []:
        if isinstance(col, dict):
            _clean_tests_in_container(
                col,
                str(col.get("name", "")).lower(),
                required_keys,
                model_required=model_required,
            )

    cols = entry.get("columns")
    if isinstance(cols, list):
        survivors = CommentedSeq()
        for col in cols:
            if (
                isinstance(col, dict)
                and _is_managed_column(col)
                and not col.get("data_tests")
                and not col.get("description")
            ):
                continue  # drop a managed column that has become empty
            survivors.append(col)
        if len(survivors):
            entry["columns"] = survivors
        else:
            entry.pop("columns", None)

    if not model_required:
        _remove_our_meta(entry)


def _run_yaml_cleanup(
    session: _EditSession,
    required: RequiredState,
    *,
    scope_contract_id: Optional[str],
) -> None:
    """Walk every loaded file and remove CLI footprint that is no longer required."""
    for path in sorted(session.files):
        pf = session.files[path]
        if pf.deleted:
            continue
        entries = _model_entries(pf.data)
        if not entries:
            continue
        owned = _is_owned_sidecar(pf.original_text)
        touched = False
        for entry in entries:
            if not _entry_in_scope(entry, scope_contract_id, required.scope_models):
                continue
            touched = True
            model_lower = str(entry.get("name", "")).lower()
            model_required = model_lower in required.scope_models
            _clean_model_entry(
                entry,
                required_keys=required.required_tests.get(model_lower, set()),
                model_required=model_required,
            )

        if owned and (touched or scope_contract_id is None):
            still_required = any(str(m.get("name", "")).lower() in required.scope_models for m in entries)
            if not still_required:
                session.delete(path)


# ---------------------------------------------------------------------------
# Legacy-dir migration + singular-SQL cleanup
# ---------------------------------------------------------------------------


def _remove_legacy_dir(legacy_dir: Path) -> List[Path]:
    """Remove the old `<model-paths>/datacontract_cli/` parallel-YAML dir (migration)."""
    if not legacy_dir.is_dir():
        return []
    shutil.rmtree(legacy_dir)
    return [legacy_dir]


def run_dbt_test(
    project_dir: Path,
    *,
    target: Optional[str],
    profiles_dir: Optional[Path],
) -> subprocess.CompletedProcess:
    # Selects every CLI-managed test (generated + adopted) by the meta key all of them carry.
    select_managed = f"config.meta.{META_NAMESPACE}.include_in_tests:true"
    args = ["dbt", "test", "--select", select_managed, "--project-dir", str(project_dir)]
    if target:
        args.extend(["--target", target])
    if profiles_dir:
        # Resolve to absolute — we cwd into project_dir below, so a relative
        # `--profiles-dir` from the user's shell would otherwise miss.
        args.extend(["--profiles-dir", str(Path(profiles_dir).resolve())])

    # Drop any prior run_results.json so we don't mistake a stale file for fresh output
    # if dbt fails before regenerating it.
    run_results_path = _resolved_target_dir(project_dir) / "run_results.json"
    if run_results_path.is_file():
        run_results_path.unlink()

    try:
        # cwd=project_dir lets dbt find a project-local profiles.yml the way users expect
        # when running `dbt test` from inside their project.
        result = subprocess.run(args, capture_output=True, text=True, check=False, cwd=str(project_dir))
    except OSError as e:
        raise DataContractException(
            type="dbt_sync",
            name="dbt test",
            reason=f"Failed to invoke dbt: {e}",
            engine="dbt-sync",
            original_exception=e,
        )

    ansi_control_chars = re.compile(r"\x1b\[[0-9;]*[mGKHF]")
    output = ansi_control_chars.sub("", (result.stderr or "") + (result.stdout or ""))
    if result.returncode != 0 and not run_results_path.is_file():
        raise DataContractException(
            type="dbt_sync",
            name="dbt test",
            reason=f"`dbt test` failed (exit code {result.returncode}):\n{output}",
            engine="dbt-sync",
        )
    return result


def _load_manifest(project_dir: Path) -> dict:
    manifest_path = _resolved_target_dir(project_dir) / "manifest.json"
    if not manifest_path.is_file():
        return {}
    try:
        with manifest_path.open("r", encoding="utf-8") as f:
            return json.load(f)
    except (OSError, json.JSONDecodeError):
        return {}


def _get_test_metadata(test_node: dict) -> Tuple[Optional[str], Optional[str], Optional[str]]:
    """Return (model, column, description) extracted from a manifest.json test node."""
    if not test_node:
        return None, None, None
    description = test_node.get("description") or None

    column = test_node.get("column_name")
    test_metadata = test_node.get("test_metadata") or {}
    kwargs = test_metadata.get("kwargs") or {}
    if not column:
        kw_col = kwargs.get("column_name")
        if isinstance(kw_col, str):
            column = kw_col

    model = None
    attached = test_node.get("attached_node")
    if isinstance(attached, str) and attached.startswith("model."):
        model = attached.split(".")[-1]
    if not model:
        for dep in (test_node.get("depends_on") or {}).get("nodes") or []:
            if isinstance(dep, str) and dep.startswith("model."):
                model = dep.split(".")[-1]
                break

    # Singular SQL tests have no `column_name` / `attached_node` in the manifest,
    # therefore we stored them to `config(meta={datacontract_cli: {...}})`.
    meta = (test_node.get("config") or {}).get("meta") or {}
    dc = meta.get(META_NAMESPACE)
    dc = dc if isinstance(dc, dict) else {}
    if not column and isinstance(dc.get("field"), str):
        column = dc["field"]
    if not model and isinstance(dc.get("model"), str):
        model = dc["model"]
    if not description and isinstance(dc.get("description"), str):
        description = dc["description"]

    return model, column, description


def parse_run_results(project_dir: Path, odcs: OpenDataContractStandard) -> Run:
    run = Run.create_run()
    run.dataContractId = odcs.id
    run.dataContractVersion = odcs.version

    run_results_path = _resolved_target_dir(project_dir) / "run_results.json"
    if not run_results_path.is_file():
        run.log_warn(f"`{run_results_path}` not found — no test results to record.")
        run.finish()
        return run

    try:
        with run_results_path.open("r", encoding="utf-8") as f:
            run_results = json.load(f)
    except (OSError, json.JSONDecodeError) as e:
        run.log_warn(f"Could not read `{run_results_path}` — {e}")
        run.finish()
        return run

    manifest = _load_manifest(project_dir)
    nodes = manifest.get("nodes") or {}

    status_map = {
        "pass": ResultEnum.passed,
        "fail": ResultEnum.failed,
        "warn": ResultEnum.warning,
        "error": ResultEnum.error,
        "skipped": ResultEnum.info,
    }
    for r in run_results.get("results") or []:
        unique_id = r.get("unique_id") or ""
        status = (r.get("status") or "").lower()
        result_enum = status_map.get(status, ResultEnum.unknown)
        failures = r.get("failures")
        message = r.get("message")
        node = nodes.get(unique_id) or {}
        model, column, description = _get_test_metadata(node)
        dc_meta = (node.get("config") or {}).get("meta") or {}
        dc_block = dc_meta.get(META_NAMESPACE) if isinstance(dc_meta.get(META_NAMESPACE), dict) else {}
        # `check` holds the fully-qualified key (`{model}__{field}__{type}`). The bare type is its
        # final `__`-segment — unambiguous because no check-type token itself contains `__`.
        check_key = dc_block.get("check") if isinstance(dc_block.get("check"), str) else None
        check_type = check_key.rsplit("__", 1)[-1] if check_key else "dbt_test"
        fallback_name = node.get("name")
        if not fallback_name:
            parts = unique_id.split(".")
            fallback_name = parts[-2] if len(parts) >= 3 else unique_id
        reason_parts = []
        if failures:
            reason_parts.append(f"failures={failures}")
        if message:
            reason_parts.append(message)
        run.checks.append(
            Check(
                key=check_key,
                type=check_type,
                name=description or fallback_name,
                model=model,
                field=column,
                engine="dbt",
                result=result_enum,
                reason=" | ".join(reason_parts) or None,
            )
        )

    run.finish()
    return run


# ---------------------------------------------------------------------------
# Top-level orchestrator
# ---------------------------------------------------------------------------


@dataclass
class DbtTestGenerationResult:
    contract_path: Path
    project_dir: Path
    odcs: OpenDataContractStandard
    resolved_models: List[str]
    written_yaml: List[Path]  # model YAML files edited or created
    written_sql: List[Path]
    deleted_files: List[Path]
    skipped_schemas: List[str]
    generation_run: Run


def _resolve_contract_path(contract: Optional[str], search_dir: Path) -> Path:
    if contract:
        contract_path = Path(contract).resolve()
        if not contract_path.is_file():
            raise DataContractException(
                type="dbt_sync",
                name="resolve contract",
                reason=f"Contract file not found: {contract_path}",
                engine="dbt-sync",
            )
        return contract_path
    return find_contract(search_dir)


def generate_dbt_tests(
    *,
    contract: Optional[str],
    project_dir: Optional[Path],
    schema_name: str = "all",
    model_resolution: ModelResolution = ModelResolution.name,
    prune: bool = False,
) -> DbtTestGenerationResult:
    """Resolve the contract, merge its tests + metadata into the dbt project's model YAML in place."""
    project_dir = (project_dir or Path.cwd()).resolve()
    _ensure_dbt_project(project_dir)

    contract_path = _resolve_contract_path(contract, project_dir)
    odcs = resolve_data_contract(str(contract_path))
    logger.info(f"Resolved contract {odcs.id}@{odcs.version} from {contract_path}")

    run = Run.create_run()
    run.dataContractId = odcs.id
    run.dataContractVersion = odcs.version

    name_map = resolve_model_names(odcs, model_resolution, schema_name)
    if not name_map:
        run.log_info("No quality to sync (contract has no schemas with names).")

    model_paths, _ = _read_dbt_project_paths(project_dir)
    legacy_dir, tests_dir = _resolved_generated_dirs(project_dir)

    # Load every model-path YAML up front so model names can be matched case-insensitively
    # against the project's actual dbt models (#1254) before we generate anything.
    session = _EditSession()
    for path in _iter_model_yaml_files(model_paths, legacy_dir):
        session.try_load(path)

    # Resolve each schema to the project's actual dbt model name (case-preserved), then build
    # the desired state (model dict + singular SQL) against that name so `ref()` / patches match.
    schemas_by_name = {s.name: s for s in (odcs.schema_ or []) if s.name}
    plans: List[_ModelPlan] = []
    skipped_schemas: List[str] = []
    for schema_name_key, contract_model_name in name_map.items():
        effective, source, sql_path = _effective_model_name(session, model_paths, contract_model_name)
        if source == "missing":
            run.log_warn(
                f"Schema `{schema_name_key}` resolves to model `{contract_model_name}`, which has no matching "
                "dbt model (no `.sql` or YAML entry) in this project — nothing to test, skipping. "
                "If the model exists under a different name, try `--model-resolution physicalName`."
            )
            skipped_schemas.append(schema_name_key)
            continue
        schema_obj = schemas_by_name[schema_name_key]
        model_dict, singulars = generate_dbt_tests_for_schema(odcs, schema_obj, effective, run)
        plans.append(_ModelPlan(effective, schema_obj, model_dict, singulars, sql_path))

    singular_tests: List[SingularTest] = [s for p in plans for s in p.singular_tests]

    required = RequiredState(
        scope_models={p.name.lower(): p.name for p in plans},
        required_tests={p.name.lower(): _required_test_keys(p.model_dict) for p in plans},
    )
    _run_yaml_cleanup(session, required, scope_contract_id=odcs.id)

    resolved_models: List[str] = []
    for plan in plans:
        located = _locate_entry(session, plan.name)
        if located is not None:
            path, entry = located
            owned = _is_owned_sidecar(session.files[path].original_text)
            _merge_model_entry(entry, plan.schema_obj, plan.model_dict, odcs, owned=owned, prune=prune)
        else:
            # source == "sql": no YAML entry anywhere → sidecar next to the model's `.sql`.
            sidecar_path = plan.sql_path.with_suffix(".yml")
            existing = session.files.get(sidecar_path)
            entry = CommentedMap()
            entry["name"] = plan.name
            if existing is not None:
                owned = _is_owned_sidecar(existing.original_text)
                models = existing.data.get("models")
                if not isinstance(models, list):
                    models = CommentedSeq()
                    existing.data["models"] = models
                models.append(entry)
                _merge_model_entry(entry, plan.schema_obj, plan.model_dict, odcs, owned=owned, prune=prune)
            else:
                session.create_sidecar(sidecar_path, entry)
                _merge_model_entry(entry, plan.schema_obj, plan.model_dict, odcs, owned=True, prune=prune)
        resolved_models.append(plan.name)

    # Singular SQL is CLI-owned wholesale: wipe + regenerate. Migrate the legacy parallel-YAML dir.
    _, tests_dir = _resolved_generated_dirs(project_dir)
    if tests_dir.exists():
        shutil.rmtree(tests_dir)
    tests_dir.mkdir(parents=True, exist_ok=True)

    written_sql = _write_singular_sql(project_dir, singular_tests)
    _remove_legacy_dir(legacy_dir)
    written_yaml, deleted_files = session.apply()

    return DbtTestGenerationResult(
        contract_path=contract_path,
        project_dir=project_dir,
        odcs=odcs,
        resolved_models=resolved_models,
        written_yaml=written_yaml,
        written_sql=written_sql,
        deleted_files=deleted_files,
        skipped_schemas=skipped_schemas,
        generation_run=run,
    )


def run_tests(
    odcs: OpenDataContractStandard,
    project_dir: Path,
    *,
    target: Optional[str] = None,
    profiles_dir: Optional[Path] = None,
    generation_run: Optional[Run] = None,
) -> Run:
    """Run `dbt test` against the contract-managed tests on disk and return the parsed results.

    `generation_run` is the `Run` from a same-invocation `generate_dbt_tests` (sync's `--run-tests`
    path); its logs and start time are stitched onto the result. `dbt test` (run-only) passes None.
    """
    completed = run_dbt_test(project_dir, target=target, profiles_dir=profiles_dir)

    parsed_run = parse_run_results(project_dir, odcs)
    ansi = re.compile(r"\x1b\[[0-9;]*[mGKHF]")
    for stream in (completed.stdout, completed.stderr):
        if not stream:
            continue
        for line in ansi.sub("", stream).splitlines():
            line = line.strip()
            if line:
                parsed_run.log_info(line)

    if generation_run is not None:
        # Stitch generation-time logs on so warn-counts include any generation-time skips.
        parsed_run.logs = generation_run.logs + parsed_run.logs
        parsed_run.timestampStart = generation_run.timestampStart
    parsed_run.finish()
    return parsed_run
