erDiagram
		"📑OrderSchema"{
	order_id string
	order_timestamp string
	order_total integer
	line_items array
	vouchers array
	customer_id string
	customer_email_address string
	processed_timestamp string
}

