# product_detail

| Type | Field | Constraints | Description |
|------|-------|-------------|-------------|
| object | identification |  |  |
| array | pharmaceuticalContent |  |  |
| array | ecommerceContent |  |  |
| array | newItemSetup |  |  |
| array | planoContent |  |  |
| array | marketingContent |  |  |

