#!/bin/bash
set -e

# Release steps:
# 1. Update release version in pyproject.toml
# 2. Update CHANGELOG.md header
# 3. Run ./release
# 4. Update release notes in Github

# pip install toml-cli
VERSION=$(uvx --from toml-cli toml get --toml-path pyproject.toml project.version)
TAG_VERSION=v$VERSION

echo "Checking that everything is committed"
git diff --exit-code
echo "Tagging $TAG_VERSION"
git tag $TAG_VERSION
echo "Pushing $TAG_VERSION"
git push origin $TAG_VERSION
echo "Pushed $TAG_VERSION"
