"""Regenerate the options listing on the docs Configuration page.

The tables are derived from `datacontract.config.Config`, so every declared
option appears with its environment variable name, `Config` field, and type.
The listing is injected between AUTOGENERATED CONFIG OPTIONS markers in
docs/docs/configuration.md; `tests/test_docs_config_options.py` fails when the
committed page is stale.
"""

from pathlib import Path

from datacontract.config import DEPRECATED_OPTIONS, SERVER_OVERRIDE_OPTIONS, Config, env_name

DOCS_PAGE = Path(__file__).parent / "docs" / "docs" / "configuration.md"

# JSX comments (not HTML comments) — MDX 3 rejects `<!-- -->`.
START = "{/* AUTOGENERATED CONFIG OPTIONS: do not edit by hand; regenerate with update_config_options.py */}"
END = "{/* END AUTOGENERATED CONFIG OPTIONS */}"

# field-name prefix -> section heading, in display order
GROUPS = {
    "entropy_data": "Entropy Data (publishing, remote contracts)",
    "datamesh_manager": "Entropy Data (publishing, remote contracts)",
    "datacontract_manager": "Entropy Data (publishing, remote contracts)",
    "api_header": "General",
    "max_errors": "General",
    "athena": "Athena",
    "azure": "Azure",
    "bigquery": "BigQuery",
    "databricks": "Databricks",
    "duckdb": "DuckDB",
    "gcs": "GCS",
    "iceberg": "Iceberg",
    "impala": "Impala",
    "kafka": "Kafka",
    "mysql": "MySQL",
    "oracle": "Oracle",
    "postgres": "Postgres",
    "redshift": "Redshift",
    "s3": "S3 / AWS (also Athena, Redshift IAM, Glue)",
    "snowflake": "Snowflake",
    "sqlserver": "SQL Server",
    "trino": "Trino",
}


def _group(field_name: str) -> str:
    for prefix, heading in GROUPS.items():
        if field_name == prefix or field_name.startswith(prefix + "_"):
            return heading
    raise ValueError(f"No docs group for Config field {field_name}; add a prefix to GROUPS.")


def _type_label(annotation) -> str:
    text = str(annotation)
    if "SecretStr" in text:
        return "string (secret)"
    if "int" in text:
        return "integer"
    if "bool" in text:
        return "boolean"
    return "string"


def render_options_block() -> str:
    sections: dict[str, list[str]] = {}
    for name, field in Config.model_fields.items():
        heading = _group(name)
        notes = ""
        if name in DEPRECATED_OPTIONS:
            replacement = DEPRECATED_OPTIONS[name]
            replacement_env = env_name(replacement, Config.model_fields[replacement])
            notes = f"Deprecated, use `{replacement_env}`"
        elif name in SERVER_OVERRIDE_OPTIONS:
            notes = f"Overrides `{SERVER_OVERRIDE_OPTIONS[name]}` from the contract's `servers` block"
        row = f"| `{env_name(name, field)}` | `{name}` | {_type_label(field.annotation)} | {notes} |"
        sections.setdefault(heading, []).append(row)

    lines = [START, ""]
    for heading, rows in sections.items():
        lines.append(f"### {heading}")
        lines.append("")
        lines.append("| Environment variable | `Config` field | Type | Notes |")
        lines.append("|---|---|---|---|")
        lines.extend(rows)
        lines.append("")
    lines.append(END)
    return "\n".join(lines)


def update_page() -> bool:
    """Rewrite the block; returns True when the page changed."""
    text = DOCS_PAGE.read_text()
    start = text.index(START)
    end = text.index(END) + len(END)
    new_text = text[:start] + render_options_block() + text[end:]
    if new_text == text:
        return False
    DOCS_PAGE.write_text(new_text)
    return True


if __name__ == "__main__":
    changed = update_page()
    print(f"{DOCS_PAGE}: {'updated' if changed else 'up to date'}")
