#!/usr/bin/env python3
"""Regenerate the command reference pages under docs/docs/commands/.

The Commands section is a pure reference: every page is derived from what
`datacontract <command> --help` prints, so it can never drift from the CLI.
Groups (`import`, `export`, `dbt`) get a folder with one sub-page per
subcommand. Prose guides live elsewhere (docs/docs/imports, exports, testing);
nothing outside docs/docs/commands/ is touched.

    python update_command_docs.py          # rewrite the pages
    python update_command_docs.py --check  # fail if anything is out of date

Re-run whenever a command, option, or help string changes.
"""

from __future__ import annotations

import json
import shutil
import sys
from pathlib import Path
from typing import Any

import typer.main

from datacontract.cli import app

# typer >= 0.27 builds its command tree from a vendored click fork, so the objects
# below are not instances of the installed `click` classes. Everything here is
# duck-typed against the click API instead of isinstance-checked.

DOCS = Path("docs/docs/commands")

# Sidebar order of the top-level commands: workflow order, not alphabetical.
COMMAND_ORDER = [
    "init",
    "edit",
    "lint",
    "changelog",
    "test",
    "dbt",
    "ci",
    "export",
    "import",
    "catalog",
    "publish",
    "api",
]

BANNER = "{/* AUTOGENERATED from `datacontract --help`: do not edit by hand; regenerate with update_command_docs.py */}"


def escape(text: str | None) -> str:
    """Make help text safe for an MDX table cell.

    MDX reads `{...}` as a JSX expression and `<...>` as a tag, both of which
    fail the docs build, so they are escaped. Backslashes are left alone: the
    help strings already escape for the terminal renderer (`\\[`), and doubling
    them would print the backslash instead of the bracket.
    """
    if not text:
        return "—"
    out = " ".join(text.split())
    for char in ("|", "<", ">", "{", "}"):
        out = out.replace(char, f"\\{char}")
    return out


def is_group(cmd: Any) -> bool:
    """A command group is a command that has subcommands."""
    return hasattr(cmd, "commands")


def format_default(param: Any) -> str:
    default = param.default
    if param.required:
        return "required"
    if default is None or default == "":
        return "—"
    if isinstance(default, bool):
        # Boolean flags read better as the flag that is on by default.
        if param.secondary_opts:
            return f"`{param.opts[0] if default else param.secondary_opts[0]}`"
        return "on" if default else "off"
    if isinstance(default, (list, tuple)):
        return "—" if not default else f"`{', '.join(str(d) for d in default)}`"
    value = getattr(default, "value", default)
    return f"`{value}`"


def metavar(param: Any) -> str:
    """`[LOCATION]`, `V1`, `[CONTRACT]...` — how an argument appears in the usage line.

    Spelled out here rather than taken from `make_metavar()`, whose signature and
    output both changed across click 8.2 and typer 0.27; the pages must render the
    same whichever version is installed.
    """
    name = param.metavar or param.name.upper()
    if not param.required:
        name = f"[{name}]"
    return name if param.nargs == 1 else f"{name}..."


def usage(cmd: Any, path: str) -> str:
    pieces = [cmd.options_metavar] if cmd.options_metavar else []
    pieces += [metavar(p) for p in cmd.params if p.param_type_name == "argument"]
    if is_group(cmd):
        pieces.append(cmd.subcommand_metavar)
    return f"datacontract {path} " + " ".join(pieces)


def arguments_table(cmd: Any) -> list[str]:
    args = [p for p in cmd.params if p.param_type_name == "argument"]
    if not args:
        return []
    rows = ["| Argument | Default | Description |", "|---|---|---|"]
    for p in args:
        rows.append(f"| `{metavar(p)}` | {format_default(p)} | {escape(getattr(p, 'help', None))} |")
    return rows + [""]


def options_table(cmd: Any) -> list[str]:
    opts = [p for p in cmd.params if p.param_type_name == "option" and not _is_help(p)]
    if not opts:
        return []
    rows = ["| Option | Default | Description |", "|---|---|---|"]
    for p in opts:
        names = " / ".join(f"`{o}`" for o in list(p.opts) + list(p.secondary_opts))
        rows.append(f"| {names} | {format_default(p)} | {escape(p.help)} |")
    return rows + [""]


def _is_help(param: Any) -> bool:
    return "--help" in param.opts


def first_sentence(text: str) -> str:
    """The frontmatter description is a one-line summary, not the full help."""
    for end in (". ", ".\n"):
        if end in text:
            return text.split(end)[0] + "."
    return text


def frontmatter(title: str, description: str, position: int) -> list[str]:
    safe = first_sentence(description).replace('"', "'")
    return [
        "---",
        f"sidebar_position: {position}",
        f'title: "{title}"',
        f'description: "{safe}"',
        "---",
        "",
    ]


def short_help(cmd: Any) -> str:
    text = (cmd.help or cmd.short_help or "").strip()
    return " ".join(text.split()) if text else "No description available."


def render_command(cmd: Any, path: str, position: int) -> str:
    """A reference page for one leaf command."""
    lines = frontmatter(path, short_help(cmd), position)
    lines += [f"# `datacontract {path}`", "", BANNER, "", short_help(cmd), ""]
    lines += ["```bash", usage(cmd, path), "```", ""]
    lines += arguments_table(cmd)
    lines += options_table(cmd)
    if cmd.epilog:
        example = cmd.epilog.strip()
        example = example[len("Example:") :].strip() if example.startswith("Example:") else example
        lines += ["```bash", example, "```", ""]
    return "\n".join(lines).rstrip() + "\n"


def render_group_index(group: Any, name: str, position: int) -> str:
    """The landing page for a command group, listing its subcommands."""
    lines = frontmatter(name, short_help(group), position)
    lines += [f"# `datacontract {name}`", "", BANNER, "", short_help(group), ""]
    lines += ["```bash", usage(group, name), "```", ""]
    lines += options_table(group)
    lines += ["| Subcommand | Description |", "|---|---|"]
    for sub_name in sorted(group.commands):
        sub = group.commands[sub_name]
        lines.append(f"| [`{sub_name}`](./{sub_name}.md) | {escape(short_help(sub))} |")
    lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def write(path: Path, content: str, changed: list[str]) -> None:
    if path.exists() and path.read_text() == content:
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)
    changed.append(str(path))


def generate(changed: list[str]) -> set[Path]:
    """Write every page; return the set of files that should exist."""
    root = typer.main.get_command(app)
    # Hand-written files the generator must never remove.
    expected: set[Path] = {DOCS / "index.md", DOCS / "_category_.json"}

    for name, cmd in root.commands.items():
        position = COMMAND_ORDER.index(name) + 1 if name in COMMAND_ORDER else 99
        if is_group(cmd):
            folder = DOCS / name
            index = folder / "index.md"
            write(index, render_group_index(cmd, name, position), changed)
            expected.add(index)
            category = folder / "_category_.json"
            write(
                category,
                json.dumps(
                    {"label": name, "position": position, "link": {"type": "doc", "id": f"commands/{name}/index"}},
                    indent=2,
                )
                + "\n",
                changed,
            )
            expected.add(category)
            for i, sub_name in enumerate(sorted(cmd.commands), start=1):
                page = folder / f"{sub_name}.md"
                write(page, render_command(cmd.commands[sub_name], f"{name} {sub_name}", i), changed)
                expected.add(page)
        else:
            page = DOCS / f"{name}.md"
            write(page, render_command(cmd, name, position), changed)
            expected.add(page)
    return expected


def main() -> int:
    check = "--check" in sys.argv
    if check:
        backup = Path(str(DOCS) + ".bak")
        shutil.copytree(DOCS, backup, dirs_exist_ok=True)

    changed: list[str] = []
    expected = generate(changed)
    stale = [p for p in DOCS.rglob("*") if p.is_file() and p not in expected]
    for path in stale:
        path.unlink()
        changed.append(f"{path} (removed)")

    if check:
        shutil.rmtree(DOCS)
        shutil.move(str(Path(str(DOCS) + ".bak")), str(DOCS))
        if changed:
            print("Command docs are out of date. Run: python update_command_docs.py")
            for c in sorted(changed):
                print(f"  {c}")
            return 1
        print("Command docs are up to date.")
        return 0

    for c in sorted(changed):
        print(f"  {c}")
    print(f"{len(changed)} file(s) written, {len(expected)} page(s) total.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
