import shutil
import subprocess
import sys
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[1]


@pytest.fixture(autouse=True)
def change_test_dir(request, monkeypatch):
    monkeypatch.chdir(request.fspath.dirname)


def _generate(command: list[str]) -> None:
    result = subprocess.run(command, cwd=REPO_ROOT, capture_output=True, text=True)
    assert result.returncode == 0, result.stdout + result.stderr


@pytest.fixture(scope="session")
def generated_docs():
    """Generate the docs pages that are built rather than committed.

    docs/docs/commands comes from the CLI's own `--help` output and
    docs/docs/release-notes.md from CHANGELOG.md, both regenerated by the docs
    build. The tests produce them the same way instead of asserting against a
    checked-in copy that a pull request would have to keep in sync.
    """
    _generate([sys.executable, "update_command_docs.py"])
    if shutil.which("node") is None:
        pytest.skip("node is needed to generate docs/docs/release-notes.md")
    _generate(["node", "docs/scripts/generate-release-notes.mjs"])
