import functools
import re
import shutil
import subprocess
import sys
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[1]


@pytest.fixture(autouse=True)
def change_test_dir(request, monkeypatch):
    monkeypatch.chdir(request.fspath.dirname)


# Whether a test file drives a testcontainers container. Matched on the file's
# text rather than on a marker, because these modules construct their container
# at import time (`postgres = PostgresContainer("postgres:16")`) — so the call
# has to be made before collection imports the module, which rules out anything
# written inside it. `Container` additionally catches test_import_trino.py,
# which imports its container class from a sibling test module rather than from
# testcontainers directly.
_NEEDS_DOCKER = re.compile(r"testcontainers|Container")

_ignored_for_docker: list[str] = []


@functools.cache
def _docker_is_available() -> bool:
    """Whether a Docker daemon is reachable for the testcontainers tests."""
    try:
        import docker
    except ImportError:
        return False
    try:
        client = docker.from_env()
    except Exception:
        return False
    try:
        return bool(client.ping())
    except Exception:
        return False
    finally:
        client.close()


def pytest_ignore_collect(collection_path: Path, config) -> bool | None:
    """Leave the container tests uncollected when there is no Docker daemon.

    The macOS GitHub runner has no Docker, and the CLI is installed with pip on
    macOS laptops as much as on Linux — so the rest of the suite is worth
    running there even though the container tests cannot be. Keying this on the
    daemon rather than on the platform keeps the container tests running on a
    developer's machine, where Docker usually is available.
    """
    if collection_path.suffix != ".py" or not collection_path.name.startswith("test_"):
        return None
    if not _NEEDS_DOCKER.search(collection_path.read_text(encoding="utf-8")):
        return None
    if _docker_is_available():
        return None
    _ignored_for_docker.append(collection_path.name)
    return True


def pytest_report_collectionfinish(config, items) -> str | None:
    """Say out loud which tests did not run, so the pass is not misread as full."""
    if not _ignored_for_docker:
        return None
    files = ", ".join(sorted(_ignored_for_docker))
    return f"no Docker daemon: not collecting {len(_ignored_for_docker)} container test files ({files})"


def _generate(command: list[str]) -> None:
    result = subprocess.run(command, cwd=REPO_ROOT, capture_output=True, text=True)
    assert result.returncode == 0, result.stdout + result.stderr


@pytest.fixture(scope="session")
def generated_docs():
    """Generate the docs pages that are built rather than committed.

    docs/docs/commands comes from the CLI's own `--help` output and
    docs/docs/release-notes.md from CHANGELOG.md, both regenerated by the docs
    build. The tests produce them the same way instead of asserting against a
    checked-in copy that a pull request would have to keep in sync.
    """
    _generate([sys.executable, "update_command_docs.py"])
    if shutil.which("node") is None:
        pytest.skip("node is needed to generate docs/docs/release-notes.md")
    _generate(["node", "docs/scripts/generate-release-notes.mjs"])
