"""The docs list every importer and exporter three times; all three stay alphabetical.

The order has drifted twice: once by appending new pages at the end, and once by
sorting on the file name when the sidebar renders the page title, which put
``Import: AWS Glue`` under G and ``Import: Amazon Redshift`` under R. Each list
is checked against the text it actually displays.
"""

import re

import pytest

from tests.docs_paths import DOCS

# The Commands section and the Release Notes page are generated by the docs
# build rather than committed, and both are listed here.
pytestmark = pytest.mark.usefixtures("generated_docs")

FOLDERS = [("imports", "Import: ", "import"), ("exports", "Export: ", "export")]
IDS = [folder for folder, _, _ in FOLDERS]

# The reference and connection guides are listed the same way, minus a command
# page to cross-check against.
SIDEBAR_FOLDERS = FOLDERS + [("reference", "", None), ("testing", "", None)]
SIDEBAR_IDS = [folder for folder, _, _ in SIDEBAR_FOLDERS]


def pages(folder: str):
    """Every listed page of the folder, index and unlisted stubs excluded."""
    listed = [
        page
        for page in (DOCS / folder).glob("*.md")
        if page.stem != "index" and "unlisted: true" not in page.read_text()
    ]
    # by stem, not by file name: "avro-idl.md" sorts before "avro.md" ("-" < ".")
    return sorted(listed, key=lambda page: page.stem)


def sidebar_label(page, prefix: str) -> str:
    """The text Docusaurus renders in the sidebar for this page."""
    text = page.read_text()
    label = re.search(r'^sidebar_label: "(.*)"$', text, re.M)
    rendered = label.group(1) if label else re.search(r'^title: "(.*)"$', text, re.M).group(1)
    return rendered.removeprefix(prefix)


def sidebar_position(page) -> int:
    return int(re.search(r"^sidebar_position: (\d+)$", page.read_text(), re.M).group(1))


@pytest.mark.parametrize("folder, prefix, _command", SIDEBAR_FOLDERS, ids=SIDEBAR_IDS)
def test_sidebar_is_ordered_by_the_label_it_renders(folder, prefix, _command):
    ordered = [sidebar_label(page, prefix) for page in sorted(pages(folder), key=sidebar_position)]

    assert ordered == sorted(ordered, key=str.lower)


@pytest.mark.parametrize("folder, prefix, _command", SIDEBAR_FOLDERS, ids=SIDEBAR_IDS)
def test_sidebar_positions_are_a_gapless_sequence(folder, prefix, _command):
    """A duplicate or a gap makes the rendered order depend on the file name again."""
    positions = sorted(sidebar_position(page) for page in pages(folder))

    assert positions == list(range(1, len(positions) + 1))


@pytest.mark.parametrize("folder, prefix, _command", FOLDERS, ids=IDS)
def test_card_grid_lists_every_page_in_order(folder, prefix, _command):
    index = (DOCS / folder / "index.md").read_text()
    grid = re.search(r'<div className="card-grid">(.*?)</div>', index, re.S).group(1)
    # the cards show the format name, so that is what has to be in order here
    titles = re.findall(r'doc-card-title">([^<]+)<', grid)

    assert titles == sorted(titles)
    assert titles == [page.stem for page in pages(folder)]


def test_the_reference_card_grid_matches_its_sidebar():
    """Its cards show the page label rather than a format name."""
    index = (DOCS / "reference" / "index.md").read_text()
    grid = re.search(r'<div className="card-grid">(.*?)</div>', index, re.S).group(1)
    titles = re.findall(r'doc-card-title">([^<]+)<', grid)

    assert titles == sorted(titles, key=str.lower)
    assert titles == [sidebar_label(page, "") for page in sorted(pages("reference"), key=sidebar_position)]


@pytest.mark.parametrize("folder, prefix, command", FOLDERS, ids=IDS)
def test_command_page_lists_every_format_in_order(folder, prefix, command):
    """The command reference is generated, so this guards the guide pages against it.

    The subcommand table may hold more than the guides do: `import unity` is a
    deprecated alias whose page is unlisted, and `export dbt` has no guide.
    """
    index = (DOCS / "commands" / command / "index.md").read_text()
    listed = re.findall(r"^\| \[`([^`]+)`\]", index, re.M)

    assert listed == sorted(listed)
    assert {page.stem for page in pages(folder)} <= set(listed)


# The llms.txt plugin emits pages in `includeOrder`, then everything it did not
# match (`includeUnmatchedLast`). A page left out is not an error at build time,
# it just silently sinks to the bottom of llms.txt -- which is how schema.md,
# service-levels.md, semantics.md, ci-cd.md, comparison.md, contributing.md, and
# entropy-data.md ended up out of reading order.
CONFIG = DOCS.parent / "docusaurus.config.ts"


def include_order() -> list[str]:
    block = re.search(r"includeOrder: \[(.*?)\]", CONFIG.read_text(), re.S).group(1)
    return re.findall(r"'([^']+)'", block)


def top_level_pages():
    """Every listed page at the docs root, in the order the sidebar renders them."""
    listed = [page for page in DOCS.glob("*.md") if "unlisted: true" not in page.read_text()]
    return sorted(listed, key=sidebar_position)


def test_llms_txt_lists_every_top_level_page():
    listed = {entry for entry in include_order() if "/" not in entry}

    assert listed == {page.name for page in top_level_pages()}


def test_llms_txt_orders_the_top_level_pages_like_the_sidebar():
    listed = [entry for entry in include_order() if "/" not in entry]

    assert listed == [page.name for page in top_level_pages()]
