"""The options listing on the Configuration docs page is generated from Config and must not drift.

The tables between the AUTOGENERATED CONFIG OPTIONS markers are produced by
update_config_options.py, so adding a Config field without regenerating is a
test failure rather than a silently stale page.
"""

from update_config_options import DOCS_PAGE, END, START, render_options_block


def test_configuration_page_lists_every_config_option():
    text = DOCS_PAGE.read_text()
    committed = text[text.index(START) : text.index(END) + len(END)]

    assert committed == render_options_block(), (
        "docs/docs/configuration.md is stale. Run: python update_config_options.py"
    )
