import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * The documentation sidebar is generated automatically from the folder
 * structure under `docs/`. Ordering is controlled via the `sidebar_position`
 * frontmatter in each page and the `_category_.json` files in each folder.
 */
const sidebars: SidebarsConfig = {
  docsSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
